### ISSUE TITLE
Integrate extra heart tracking into food journal

### ISSUE THREAD

**Issue by wlhlm** [GTNewHorizons/SpiceOfLife#10]
Spice of Life comes with the food journal to keep track of the food a players has eaten. My suggestion is to add a page to that shows the status of the extra hearts a players has received. Basically, it should include all the information from the `/foodlist` command. The purpose is to provide an alternative way for this information to be displayed that might (or might not) be easier to discover than a command.

**Comment by mitchej123** [comment]
Book enhancements are on the wishlist, but involve GUI work that I'm terrible with -- if anyone wants to help out, I can provide the interface for the information fairly easily.
