### ISSUE TITLE
Max additional hearts config request

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/SpiceOfLife#11]
I'd like to be able to limit it to 10, since personally I think that's a useful but balanced amount (and even), and doesn't make the tinker's hearts useless.

**Comment by Dream-Master** [comment]
Yes we need a config option for it before i make a new release and we need one for how many food ou need to eat before you got a new heart

**Comment by mitchej123** [comment]
1) Please direct balancing suggestions to this thread: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5778   Answer the questions I have.  Throwing 10 out there without any input is not helpful.

2) I'll look into adding a config to make additional hearts harder.  Something like 10 food for the first row, then like 20, 30, etc.

**Comment by Prometheus0000** [comment]
I'm just saying that's what I personally want to set it to. I figured I would need a reason to request a config option. I'm already past the point where I'd be able to contribute to a discussion on the balance difference in the early game, so I don't think my opinion there would be especially useful.
