### ISSUE TITLE
Spice of Life Class file flagged as Trojan

### ISSUE THREAD

**Issue by Zelda-Swordsman** [GTNewHorizons/SpiceOfLife#21]
My antivirus, Bitdefender, just updated and flagged squeek/spiceoflife/shadow/com/udojava/evalex/Expression$Tokenizer.class for apparently being infected with Java.Trojan.GenericGBA.31479 when launching GT New Horizons. 

I am using SpiceOfLife v2.0.0-carrot-beta10.

This issue seems to also be present in v2.0.1 as an attempt to download that version was met with the same warning of the webpage and the file being infected citing the threat as Java.Trojan.GenericGBA.31479
![Screenshot 2022-05-03 170710](https://user-images.githubusercontent.com/36285521/166566419-2cb8fc71-43ef-45ca-9ed5-e016008bf546.png)

**Comment by Chaoschaot232** [comment]
Can approve this with the current available 2.0.1-carrot ones as I wanted to download it via chrome and even with disabled security including compleat MS Defender it is blocking the chrome download and reports this file as "Virus detected"

![image](https://user-images.githubusercontent.com/1703441/166607479-49397cdb-af62-4213-ba4e-3c2a76e13eed.png)

Take a look at the bottom in the image above.

Funfact: Only the regular file counts as infected but not the other ones which is interesting 🤔

**Comment by Chaoschaot232** [comment]
@Zelda-Swordsman - Try to dowload from here http://jenkins.usrv.eu:8080/job/SpiceOfLife/ it wasn't flagged so maybe it works on your side too 🤔

**Comment by glowredman** [comment]
Resolved, see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10267
