### ISSUE TITLE
HAUNCHES_PER_MILESTONE should be Configurable

### ISSUE THREAD

**Issue by Fatih120** [GTNewHorizons/SpiceOfLife#37]
In newer versions of this mod, the user is able to change how much food they need to eat before they get a heart (in those versions it's more about unique foods, but that's a separate feature). It would be nice to be able to raise or lower this for the sake of other personal packs, along with HEARTS_PER_MILESTONE for those who need it.

**Comment by DrParadox7** [comment]
Closed by #32

**Comment by DrParadox7** [comment]
@Dream-Master this can be closed as complete
