### ISSUE TITLE
Gregtech foods all counted as the same item

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/SpiceOfLife#5]
For the purpose of adding hearts, all of the gregtech foods (such as the various sandwiches, pizzas, potatoes on sticks, bread items, etc.) seem to be counted as the same item. 
Looks like this is because they're all the same item ID, and use metadata changes to distinguish between them. 
Oddly doesn't apply to the diminishing returns, only to the extra hearts.

**Comment by mitchej123** [comment]
Might be fixed with beta-2; need to test

**Comment by Prometheus0000** [comment]
This appears to be mostly fixed. They contribute different shanks, but still show up in nei when searching for not yet eaten
