### ISSUE TITLE
Eating Bowl

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/SpiceOfLife#8]
I tested a bit your new version and find out if a empty bowl is in the launch bag you can still eat and never stop. You not get any saturation.
![image](https://user-images.githubusercontent.com/2970688/76548847-adf77c80-648f-11ea-8a0f-50fcf45b2c2b.png)
And the bag shows food inside
![image](https://user-images.githubusercontent.com/2970688/76548881-bb146b80-648f-11ea-85c9-1e8b08299f30.png)
![image](https://user-images.githubusercontent.com/2970688/76548892-bea7f280-648f-11ea-926c-ef844cb759f1.png)

**Comment by DrParadox7** [comment]
Can't reproduce (anymore). 
Can close

**Comment by Dream-Master** [comment]
yea its a very old issue. maybe its fixed
